package greendao.ct7liang.weight;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ct7liang.weight.bean.Weight;

import greendao.ct7liang.weight.WeightDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig weightDaoConfig;

    private final WeightDao weightDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        weightDaoConfig = daoConfigMap.get(WeightDao.class).clone();
        weightDaoConfig.initIdentityScope(type);

        weightDao = new WeightDao(weightDaoConfig, this);

        registerDao(Weight.class, weightDao);
    }
    
    public void clear() {
        weightDaoConfig.clearIdentityScope();
    }

    public WeightDao getWeightDao() {
        return weightDao;
    }

}
