package greendao.ct7liang.weight;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.ct7liang.weight.bean.Weight;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WEIGHT".
*/
public class WeightDao extends AbstractDao<Weight, Long> {

    public static final String TABLENAME = "WEIGHT";

    /**
     * Properties of entity Weight.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Am = new Property(1, float.class, "am", false, "AM");
        public final static Property Pm = new Property(2, float.class, "pm", false, "PM");
        public final static Property Year = new Property(3, String.class, "year", false, "YEAR");
        public final static Property Month = new Property(4, String.class, "month", false, "MONTH");
        public final static Property Day = new Property(5, String.class, "day", false, "DAY");
        public final static Property Time = new Property(6, long.class, "time", false, "TIME");
    }


    public WeightDao(DaoConfig config) {
        super(config);
    }
    
    public WeightDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WEIGHT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"AM\" REAL NOT NULL ," + // 1: am
                "\"PM\" REAL NOT NULL ," + // 2: pm
                "\"YEAR\" TEXT," + // 3: year
                "\"MONTH\" TEXT," + // 4: month
                "\"DAY\" TEXT," + // 5: day
                "\"TIME\" INTEGER NOT NULL );"); // 6: time
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WEIGHT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Weight entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindDouble(2, entity.getAm());
        stmt.bindDouble(3, entity.getPm());
 
        String year = entity.getYear();
        if (year != null) {
            stmt.bindString(4, year);
        }
 
        String month = entity.getMonth();
        if (month != null) {
            stmt.bindString(5, month);
        }
 
        String day = entity.getDay();
        if (day != null) {
            stmt.bindString(6, day);
        }
        stmt.bindLong(7, entity.getTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Weight entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindDouble(2, entity.getAm());
        stmt.bindDouble(3, entity.getPm());
 
        String year = entity.getYear();
        if (year != null) {
            stmt.bindString(4, year);
        }
 
        String month = entity.getMonth();
        if (month != null) {
            stmt.bindString(5, month);
        }
 
        String day = entity.getDay();
        if (day != null) {
            stmt.bindString(6, day);
        }
        stmt.bindLong(7, entity.getTime());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Weight readEntity(Cursor cursor, int offset) {
        Weight entity = new Weight( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getFloat(offset + 1), // am
            cursor.getFloat(offset + 2), // pm
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // year
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // month
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // day
            cursor.getLong(offset + 6) // time
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Weight entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAm(cursor.getFloat(offset + 1));
        entity.setPm(cursor.getFloat(offset + 2));
        entity.setYear(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setMonth(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setDay(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTime(cursor.getLong(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Weight entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Weight entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Weight entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
